package ngordnet;
import java.util.ArrayList;

/** A utility class for reading in Synsets from the Synset input file.
 *  Stores all the synsets in a SynsetLookupTable.
 *  @author Joshua Leath
 */
public class SynsetParser {
    private int currChar;
    private SynsetLookupTable table;

    public SynsetParser() {
        table = new SynsetLookupTable();
        currChar = 0;
    }

    /** Builds and returns a synset from the String LINE. */
    public Synset buildSynset(String line) {
        int id = getSynsetId(line);
        ArrayList<String> synonyms = getWords(line);
        for (String s : synonyms) {
            table.add(s, id);
        }
        currChar = 0;
        return new Synset(id, synonyms);
    }

    /** Returns the SynsetLookupTable generated by reading the data
     *  in the synsets file found in the wordnet directory. */
    public SynsetLookupTable getLookupTable() {
        return table;
    }
    
    /** Reads the synset's id from the synsets file. */
    private int getSynsetId(String line) {
        int id = 0;
        while (line.charAt(currChar) != ',') {
            id = (id * 10) + Character.getNumericValue(line.charAt(currChar));
            currChar = currChar + 1;
        }
        currChar = currChar + 1;
        return id;
    }

    /** Builds a list of words from a single synset and returns it. */
    private ArrayList<String> getWords(String line) {
        StringBuilder wordBuilder = new StringBuilder();
        ArrayList<String> words = new ArrayList<String>();
        while (line.charAt(currChar) != ',') {
            if (line.charAt(currChar) == ' ') {
                String word = wordBuilder.toString();
                words.add(word);
                wordBuilder = new StringBuilder();
            } else {
                wordBuilder.append(line.charAt(currChar));
            }
            currChar = currChar + 1;
        }
        String word = wordBuilder.toString();
        words.add(word);
        return words;
    }
}
